import { useEffect, useState } from "react";

async function fetchDoors() {
  return [
    {
      id: "d1",
      name: "Aluminium-Haustür",
      price: 2352.41,
      //   discount: 0.35,
      rating: 5,
      images: ["/images/door2.png"],
      category: "Innentüren",
      material: "Eichenholz",
      glazing: "Teilglas",
      color: "green",
      height: 2000,
    },
    {
      id: "d2",
      name: "Aluminium-Haustür",
      price: 3000.41,
      //   discount: 0.35,
      rating: 5,
      images: ["/images/door2.png"],
      category: "Außentüren",
      material: "Bronze",
      glazing: "Teilglas",
      color: "black",
      height: 2000,
    },
    {
      id: "d3",
      name: "Aluminium-Haustür",
      price: 2352.41,
      //   discount: 0.35,
      rating: 5,
      images: ["/images/door2.png"],
      category: "Außentüren",
      material: "Eichenholz",
      glazing: "Teilglas",
      color: "black",
      height: 2000,
    },
    {
      id: "d4",
      name: "Aluminium-Haustür",
      price: 2352.41,
      //   discount: 0.35,
      rating: 5,
      images: ["/images/door2.png"],
      category: "Innentüren",
      material: "Eichenholz",
      glazing: "Teilglas",
      color: "green",
      height: 2000,
    },
    {
      id: "d5",
      name: "Aluminium-Haustür",
      price: 3000.41,
      //   discount: 0.35,
      rating: 5,
      images: ["/images/door2.png"],
      category: "Außentüren",
      material: "Bronze",
      glazing: "Teilglas",
      color: "black",
      height: 2000,
    },
    {
      id: "d6",
      name: "Aluminium-Haustür",
      price: 2352.41,
      //   discount: 0.35,
      rating: 5,
      images: ["/images/door2.png"],
      category: "Außentüren",
      material: "Eichenholz",
      glazing: "Teilglas",
      color: "black",
      height: 2000,
    },
    {
      id: "d7",
      name: "Aluminium-Haustür",
      price: 2352.41,
      //   discount: 0.35,
      rating: 5,
      images: ["/images/door2.png"],
      category: "Außentüren",
      material: "Eichenholz",
      glazing: "Teilglas",
      color: "black",
      height: 2000,
    },
    {
      id: "d8",
      name: "Aluminium-Haustür",
      price: 2352.41,
      rating: 5,
      images: ["/images/door2.png"],
      category: "Innentüren",
      material: "Eichenholz",
      glazing: "Teilglas",
      color: "green",
      height: 2000,
    },
    {
      id: "d9",
      name: "Aluminium-Haustür",
      price: 3000.41,
      rating: 5,
      images: ["/images/door2.png"],
      category: "Außentüren",
      material: "Bronze",
      glazing: "Teilglas",
      color: "black",
      height: 2000,
    },
    {
      id: "d10",
      name: "Aluminium-Haustür",
      price: 2352.41,
      //   discount: 0.35,
      rating: 5,
      images: ["/images/door2.png"],
      category: "Außentüren",
      material: "Eichenholz",
      glazing: "Teilglas",
      color: "black",
      height: 2000,
    },
  ];
}

export function useDoors() {
  const [doors, setDoors] = useState(null);
  const [error, setError] = useState(null);

  useEffect(() => {
    fetchDoors().then(setDoors).catch(setError);
  }, []);

  return { doors, error };
}
